// Code generated by go-swagger; DO NOT EDIT.

package actions_service

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewStartClickHouseExplainActionParams creates a new StartClickHouseExplainActionParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewStartClickHouseExplainActionParams() *StartClickHouseExplainActionParams {
	return &StartClickHouseExplainActionParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewStartClickHouseExplainActionParamsWithTimeout creates a new StartClickHouseExplainActionParams object
// with the ability to set a timeout on a request.
func NewStartClickHouseExplainActionParamsWithTimeout(timeout time.Duration) *StartClickHouseExplainActionParams {
	return &StartClickHouseExplainActionParams{
		timeout: timeout,
	}
}

// NewStartClickHouseExplainActionParamsWithContext creates a new StartClickHouseExplainActionParams object
// with the ability to set a context for a request.
func NewStartClickHouseExplainActionParamsWithContext(ctx context.Context) *StartClickHouseExplainActionParams {
	return &StartClickHouseExplainActionParams{
		Context: ctx,
	}
}

// NewStartClickHouseExplainActionParamsWithHTTPClient creates a new StartClickHouseExplainActionParams object
// with the ability to set a custom HTTPClient for a request.
func NewStartClickHouseExplainActionParamsWithHTTPClient(client *http.Client) *StartClickHouseExplainActionParams {
	return &StartClickHouseExplainActionParams{
		HTTPClient: client,
	}
}

/*
StartClickHouseExplainActionParams contains all the parameters to send to the API endpoint

	for the start click house explain action operation.

	Typically these are written to a http.Request.
*/
type StartClickHouseExplainActionParams struct {
	// Body.
	Body StartClickHouseExplainActionBody

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the start click house explain action params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *StartClickHouseExplainActionParams) WithDefaults() *StartClickHouseExplainActionParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the start click house explain action params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *StartClickHouseExplainActionParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the start click house explain action params
func (o *StartClickHouseExplainActionParams) WithTimeout(timeout time.Duration) *StartClickHouseExplainActionParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the start click house explain action params
func (o *StartClickHouseExplainActionParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the start click house explain action params
func (o *StartClickHouseExplainActionParams) WithContext(ctx context.Context) *StartClickHouseExplainActionParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the start click house explain action params
func (o *StartClickHouseExplainActionParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the start click house explain action params
func (o *StartClickHouseExplainActionParams) WithHTTPClient(client *http.Client) *StartClickHouseExplainActionParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the start click house explain action params
func (o *StartClickHouseExplainActionParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the start click house explain action params
func (o *StartClickHouseExplainActionParams) WithBody(body StartClickHouseExplainActionBody) *StartClickHouseExplainActionParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the start click house explain action params
func (o *StartClickHouseExplainActionParams) SetBody(body StartClickHouseExplainActionBody) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *StartClickHouseExplainActionParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {
	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
