/*
 * ⚠️⚠️⚠️ THIS FILE WAS SCAFFOLDED BY `@grafana/create-plugin`. DO NOT EDIT THIS FILE DIRECTLY. ⚠️⚠️⚠️
 *
 * In order to extend the configuration follow the steps in
 * https://grafana.com/developers/plugin-tools/create-a-plugin/extend-a-plugin/extend-configurations#extend-the-webpack-config
 */

import CopyWebpackPlugin from 'copy-webpack-plugin';
import ESLintPlugin from 'eslint-webpack-plugin';
import ForkTsCheckerWebpackPlugin from 'fork-ts-checker-webpack-plugin';
import LiveReloadPlugin from 'webpack-livereload-plugin';
import path from 'path';
import ReplaceInFileWebpackPlugin from 'replace-in-file-webpack-plugin';
import { Configuration } from 'webpack';
import less from 'less';

import { getPackageJson, getPluginJson, hasReadme, getEntries, isWSL } from './utils';
import { SOURCE_DIR, DIST_DIR } from './constants';

const pluginJson = getPluginJson();

const config = async (env): Promise<Configuration> => {
  const baseConfig: Configuration = {
    cache: {
      type: 'filesystem',
      buildDependencies: {
        config: [__filename],
      },
    },

    context: path.join(process.cwd(), SOURCE_DIR),

    devtool: env.production ? 'source-map' : 'eval-source-map',

    entry: await getEntries(),

    externals: [
      'lodash',
      'jquery',
      'moment',
      'slate',
      'emotion',
      '@emotion/react',
      '@emotion/css',
      'prismjs',
      'slate-plain-serializer',
      '@grafana/slate-react',
      'react',
      'react-dom',
      'react-redux',
      'redux',
      'rxjs',
      'react-router',
      'react-router-dom',
      'd3',
      'angular',
      '@grafana/ui',
      '@grafana/runtime',
      '@grafana/data',

      // Mark legacy SDK imports as external if their name starts with the "grafana/" prefix
      ({ request }, callback) => {
        const prefix = 'grafana/';
        const hasPrefix = (request) => request.indexOf(prefix) === 0;
        const stripPrefix = (request) => request.substr(prefix.length);

        if (hasPrefix(request)) {
          return callback(undefined, stripPrefix(request));
        }

        callback();
      },
    ],

    mode: env.production ? 'production' : 'development',

    optimization: {
      splitChunks: {
        chunks: 'all',
        cacheGroups: {
          default: false,
          defaultVendors: false,
          antdCore: {
            test: /[\\/]node_modules[\\/]antd[\\/]/,
            name: 'pmm-qan/vendor-antd-core',
            priority: 40,
            enforce: true,
          },
          antdDesign: {
            test: /[\\/]node_modules[\\/]@ant-design[\\/]/,
            name: 'pmm-qan/vendor-ant-design',
            priority: 39,
            enforce: true,
          },
          rcComponents: {
            test: /[\\/]node_modules[\\/]rc-[^\\/]+[\\/]/,
            name: 'pmm-qan/vendor-rc',
            priority: 38,
            enforce: true,
          },
          scopedRcComponents: {
            test: /[\\/]node_modules[\\/]@rc-component[\\/]/,
            name: 'pmm-qan/vendor-rc-scoped',
            priority: 38,
            enforce: true,
          },
          horizontalStackedBar: {
            test: /[\\/]node_modules[\\/]react-horizontal-stacked-bar-chart[\\/]/,
            name: 'pmm-qan/vendor-horizontal-stacked-bar',
            priority: 37,
            enforce: true,
          },
          tippy: {
            test: /[\\/]node_modules[\\/](@tippyjs[\\/]react|tippy\.js|@popperjs[\\/]core)[\\/]/,
            name: 'pmm-qan/vendor-tippy',
            priority: 36,
            enforce: true,
          },
          table: {
            test: /[\\/]node_modules[\\/]react-table[\\/]/,
            name: 'pmm-qan/vendor-table',
            priority: 35,
            enforce: true,
          },
          formState: {
            test: /[\\/]node_modules[\\/](final-form|react-final-form)[\\/]/,
            name: 'pmm-qan/vendor-form-state',
            priority: 34,
            enforce: true,
          },
          simplebar: {
            test: /[\\/]node_modules[\\/](simplebar-core|simplebar-react)[\\/]/,
            name: 'pmm-qan/vendor-simplebar',
            priority: 33,
            enforce: true,
          },
          resizeObserver: {
            test: /[\\/]node_modules[\\/]resize-observer-polyfill[\\/]/,
            name: 'pmm-qan/vendor-resize-observer',
            priority: 32,
            enforce: true,
          },
          viewport: {
            test: /[\\/]node_modules[\\/](react-viewport-list|react-split-pane)[\\/]/,
            name: 'pmm-qan/vendor-viewport',
            priority: 31,
            enforce: true,
          },
          axios: {
            test: /[\\/]node_modules[\\/]axios[\\/]/,
            name: 'pmm-qan/vendor-axios',
            priority: 30,
            enforce: true,
          },
          uiUtilities: {
            test: /[\\/]node_modules[\\/](react-style-proptype|@ctrl[\\/]tinycolor|throttle-debounce|exponential-backoff|react-lifecycles-compat|prop-types)[\\/]/,
            name: 'pmm-qan/vendor-ui-utilities',
            priority: 30,
            enforce: true,
          },
          charts: {
            test: /[\\/]node_modules[\\/](chart\.js|react-chartjs-2|chartjs-plugin-datalabels)[\\/]/,
            name: 'pmm-qan/vendor-charts',
            priority: 29,
            enforce: true,
          },
          highlight: {
            test: /[\\/]node_modules[\\/]highlight\.js[\\/]/,
            name: 'pmm-qan/vendor-highlight',
            priority: 20,
            enforce: true,
          },
          sqlFormatter: {
            test: /[\\/]node_modules[\\/]sql-formatter[\\/]/,
            name: 'pmm-qan/vendor-sql-formatter',
            priority: 19,
            enforce: true,
          },
          reactJsonView: {
            test: /[\\/]node_modules[\\/]@microlink[\\/]react-json-view[\\/]/,
            name: 'pmm-qan/vendor-react-json-view',
            priority: 18,
            enforce: true,
          },
          lodash: {
            test: /[\\/]node_modules[\\/](lodash|lodash-es)[\\/]/,
            name: 'pmm-qan/vendor-lodash',
            priority: 10,
            enforce: true,
          },
          runtime: {
            test: /[\\/]node_modules[\\/](classnames|numeral|react-is|regenerator-runtime)[\\/]/,
            name: 'pmm-qan/vendor-runtime',
            priority: 9,
            enforce: true,
          },
        },
      },
    },

    performance: {
      assetFilter: (assetFilename) => assetFilename.endsWith('.js'),
    },

    module: {
      rules: [
        {
          exclude: /(node_modules)/,
          test: /\.[tj]sx?$/,
          use: {
            loader: 'swc-loader',
            options: {
              jsc: {
                baseUrl: path.resolve(__dirname, 'src'),
                target: 'es2015',
                loose: false,
                parser: {
                  syntax: 'typescript',
                  tsx: true,
                  decorators: false,
                  dynamicImport: true,
                },
              },
            },
          },
        },
        {
          test: /\.css$/,
          use: ['style-loader', 'css-loader'],
        },
        {
          test: /\.less$/i,
          use: [
            // compiles Less to CSS
            'style-loader',
            'css-loader',
            {
              loader: 'less-loader',
              options: { implementation: less, lessOptions: { javascriptEnabled: true, math: 'always' } },
            },
          ],
        },
        {
          test: /\.s[ac]ss$/,
          use: ['style-loader', 'css-loader', 'sass-loader'],
        },
        {
          test: /\.(png|jpe?g|gif|svg)$/,
          type: 'asset/resource',
          generator: {
            // Keep publicPath relative for host.com/grafana/ deployments
            publicPath: `public/plugins/${pluginJson.id}/img/`,
            outputPath: 'img/',
            filename: Boolean(env.production) ? '[hash][ext]' : '[file]',
          },
        },
        {
          test: /\.(woff|woff2|eot|ttf|otf)(\?v=\d+\.\d+\.\d+)?$/,
          type: 'asset/resource',
          generator: {
            // Keep publicPath relative for host.com/grafana/ deployments
            publicPath: `public/plugins/${pluginJson.id}/fonts/`,
            outputPath: 'fonts/',
            filename: Boolean(env.production) ? '[hash][ext]' : '[name][ext]',
          },
        },
      ],
    },

    output: {
      clean: {
        keep: new RegExp(`(.*?_(amd64|arm(64)?)(.exe)?|go_plugin_build_manifest)`),
      },
      filename: '[name].js',
      library: {
        type: 'amd',
      },
      path: path.resolve(process.cwd(), DIST_DIR),
      publicPath: `public/plugins/${pluginJson.id}/`,
      uniqueName: pluginJson.id,
    },

    plugins: [
      new CopyWebpackPlugin({
        patterns: [
          // If src/README.md exists use it; otherwise the root README
          // To `compiler.options.output`
          { from: hasReadme() ? 'README.md' : '../README.md', to: '.', force: true },
          { from: 'plugin.json', to: '.' },
          { from: '../LICENSE', to: '.' },
          { from: '../CHANGELOG.md', to: '.', force: true },
          { from: '**/*.json', to: '.' }, // TODO<Add an error for checking the basic structure of the repo>
          { from: '**/*.svg', to: '.', noErrorOnMissing: true }, // Optional
          { from: '**/*.png', to: '.', noErrorOnMissing: true }, // Optional
          { from: '**/*.html', to: '.', noErrorOnMissing: true }, // Optional
          { from: 'img/**/*', to: '.', noErrorOnMissing: true }, // Optional
          { from: 'libs/**/*', to: '.', noErrorOnMissing: true }, // Optional
          { from: 'static/**/*', to: '.', noErrorOnMissing: true }, // Optional
        ],
      }),
      // Replace certain template-variables in the README and plugin.json
      new ReplaceInFileWebpackPlugin([
        {
          dir: DIST_DIR,
          files: ['plugin.json', 'README.md'],
          rules: [
            {
              search: /\%VERSION\%/g,
              replace: getPackageJson().version,
            },
            {
              search: /\%TODAY\%/g,
              replace: new Date().toISOString().substring(0, 10),
            },
            {
              search: /\%PLUGIN_ID\%/g,
              replace: pluginJson.id,
            },
          ],
        },
      ]),
      new ForkTsCheckerWebpackPlugin({
        async: Boolean(env.development),
        issue: {
          include: [{ file: '**/*.{ts,tsx}' }],
        },
        typescript: { configFile: path.join(process.cwd(), 'tsconfig.json') },
      }),
      new ESLintPlugin({
        extensions: ['.ts', '.tsx'],
        lintDirtyModulesOnly: Boolean(env.development), // don't lint on start, only lint changed files
      }),
      ...(env.development ? [new LiveReloadPlugin()] : []),
    ],

    resolve: {
      extensions: ['.js', '.jsx', '.ts', '.tsx'],
      // handle resolving "rootDir" paths
      modules: [path.resolve(process.cwd(), 'src'), 'node_modules'],
      unsafeCache: true,
    },
  };

  if (isWSL()) {
    baseConfig.watchOptions = {
      poll: 3000,
      ignored: /node_modules/,
    };
  }

  return baseConfig;
};

export default config;
